export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'

export const REDUCE_CREATE_ERROR = 'REDUCE_CREATE_ERROR'
export const REDUCE_DELETE_ERROR = 'REDUCE_DELETE_ERROR'

export const RESET = 'RESET'

export const REDUCE_CREATE_USER = 'REDUCE_CREATE_USER'
export const REDUCE_EDIT_USER = 'REDUCE_EDIT_USER'
