export const GLOBAL_ACTION = {
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  ADD_TOAST: 'ADD_TOAST',
  REMOVE_TOAST: 'REMOVE_TOAST',
}

export const AUTH_ACTION = {
  LOGIN_REQUEST: 'AUTH_ACTION/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_ACTION/LOGIN_SUCCESS',
  LOGIN_ERROR: 'AUTH_ACTION/LOGIN_ERROR',
  GET_CURRENT_USER: 'AUTH_ACTION/GET_CURRENT_USER',
  GET_CURRENT_USER_SUCCESS: 'AUTH_ACTION/GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_ERROR: 'AUTH_ACTION/GET_CURRENT_USER_ERROR',
  LOG_OUT: 'AUTH_ACTION/LOG_OUT',
  SET_LANG: 'SET_LANG',
}
